### ISSUE TITLE
More Extensions

### ISSUE THREAD

**Issue by endoleg** [JustinGrote/powershell-extension-pack#1]
What do you think about
https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments

and

https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2

**Comment by JustinGrote** [comment]
Bracket Pair Colorizer is already there, and better comments was eschewed in favor of TODO tree which provides similar functionality but also a viewer pane to organize the comments as a nice project workflow.

Thank you for suggesting!
