### ISSUE TITLE
gremlins

### ISSUE THREAD

**Issue by alta4096** [JustinGrote/powershell-extension-pack#2]
Hi,
Would it be possible to add a linter for characters:
https://marketplace.visualstudio.com/items?itemName=nhoizey.gremlins

Also, if it is possible to remove [bracket pair colorizer 2](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2) as it is now located in the settings area.  (https://code.visualstudio.com/blogs/2021/09/29/bracket-pair-colorization)

**Comment by JustinGrote** [comment]
Closing the loop on this (sorry it took me so long)

VSCode has native support for both of these so no changes need to be made (I removed BPC2 earlier)
https://github.com/microsoft/vscode/pull/137508https://github.com/microsoft/vscode/pull/137508

Thanks for your submission!
